name: formHCR
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - opencv
  - pillow==9.5.0
  - pdf2image
  - pandas
  - xlsxwriter
  - pip
  - pip:
      - imutils
      - zxing-cpp
      - google-cloud-vision
      - rtree
      - boto3
      - azure-cognitiveservices-vision-computervision
      - pyzbar
