name: formHCR
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - opencv
  - pillow==9.5.0
  - scikit-image
  - pdf2image
  - openpyxl
  - pandas
  - xlsxwriter
  - easyocr
  - poppler
  - pip
  - pip:
      - imutils
